projection :
  type : "orthographic" # or perspective
  fov : 35.0 #Relevant only if projection is perspective
primitive: "triangles"
clipping:
  left:   -100.0
  right:   100.0
  bottom:  100.0
  top:     100.0
  near:   -100.0
  far:     100.0
controls:
  sensitivity:  10 # every arrow key